version: '3.8'

services:
  # FastAPI ilovasi
  web:
    build:
      context: .
    image: fast_doc
    command: uvicorn project.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/project
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  # Nginx serveri
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

  # PostgreSQL ma'lumotlar bazasi
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=DB_USER
      - POSTGRES_PASSWORD=DB_PASS
      - POSTGRES_DB=DB_NAME

volumes:
  postgres_data:
